[params]
dateFormat = "2006-01-02"
copyright = "Copyright &copy; by Haruaki Tamada. Made with [Hugo](https://gohugo.io/). Deployed to [GitHub Pages](https://pages.github.com/)."

[params.author]
name = "Haruaki Tamada"
image = "https://github.com/tamada.png"
links = [
    { github = "https://github.com/tamada" },
]

[header]
showAppearanceSwitcher = true
